// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlxhfuizdrkqrcwejfif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRseGhmdWl6ZHJrcXJjd2VqZmlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NTQ3NzksImV4cCI6MjA3MDIzMDc3OX0.l8NbgfJqfLN98tGm1-FQ7ZfGiDdGDpFpvslUCRtzlfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});